### ISSUE TITLE
Panic on `clone` since `v0.22.0`

### ISSUE THREAD

**Issue by mgudemann** [obcode/glabs#39]
I get the following panic when cloning a per-group assignment since `v0.22.0`, `v0.21.0` works.
```
∙●∙ cloning git@gitlab.lrz.de:mgu_exercises/krypto/wise2024/blatt3/blatt3-grp01 to /home/guedemann/HM/WiSe2024/Krypto/Abgaben/Blatt3/blatt3-grp01 branch main/home/guedemann/HM/WiSe2024/Krypto/Abgaben/Blatt3/blatt3-grp01
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xba8472]

goroutine 1 [running]:
github.com/theckman/yacspin.(*Spinner).stop(0xf76520?, 0x58?)
        /home/guedemann/go/pkg/mod/github.com/theckman/yacspin@v0.13.12/spinner.go:652 +0x12
github.com/theckman/yacspin.(*Spinner).Stop(...)
        /home/guedemann/go/pkg/mod/github.com/theckman/yacspin@v0.13.12/spinner.go:640
github.com/obcode/glabs/git.clone({0xc0000408c0, 0x3e}, {0xd9f4c9, 0x4}, {0xc000170aa0, 0x43}, {0x0, 0x0}, 0x0, 0x0)
        /home/guedemann/source/git/glabs/git/clone.go:121 +0xabd
github.com/obcode/glabs/git.Clone(0xc000166300, 0x0)
        /home/guedemann/source/git/glabs/git/clone.go:33 +0x450
github.com/obcode/glabs/cmd.init.func2(0xc000806100?, {0xc00080a300?, 0x4?, 0xd9f3ed?})
        /home/guedemann/source/git/glabs/cmd/clone.go:36 +0x1b6
github.com/spf13/cobra.(*Command).execute(0x16082a0, {0xc00080a2c0, 0x2, 0x2})
        /home/guedemann/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x1609100)
        /home/guedemann/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        /home/guedemann/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/obcode/glabs/cmd.Execute(...)
        /home/guedemann/source/git/glabs/cmd/root.go:40
main.main()
        /home/guedemann/source/git/glabs/main.go:23 +0x105
```
Using option `-s` to suppress spinner in `clone` output does work.

**Comment by obcode** [comment]
This is fixed, isn't it?
